### ISSUE TITLE
How to perform fine tuning for classification. 

### ISSUE THREAD

**Issue by MuhammadIrzam447** [NX-AI/vision-lstm#4]
I have been able to use the .yaml files in the pretrain directory to start the training on custom datasets. However, when I try to perform the fine tuning by using the example.yaml file at "/vision-lstm/src/vislstm/yamls/vil/pretrain/pooling/finetune" and it does not work. 

I am running the whole setup on a single GPU using the following command for pretraining
```
CUDA_VISIBLE_DEVICES=3 python main_train.py --devices 3 --hp vislstm/yamls/vil/pretrain/lstm_6M16_e400_bialter_bilatavg_lr1e3_res224.yaml
```

Meanwhile, the issue arises for the fine tuning. I am downloading the models and putting them in the "/vision-lstm/src/models/.." but for some reason it does not seem to work. 
The error originates from the "kwargs in model attributes in example.yaml" file. 

The values are as follows:
```
model:
  kind: models.single.vislstm
  patch_size: 16
  kwargs: ${select:tiny:${yaml:vision-lstm/src/models/vil_tiny16_e400_in1k}}
  mode: classifier
  pooling:
    kind: class_token
```
